name: flutter_clean_architecture
description: Flutter Clean Architecture
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  get_it: ^7.6.2
  google_fonts: ^6.0.0
  intl: ^0.18.1
  json_serializable: ^6.7.0
  loggy: ^2.0.3
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.production
    - .env.staging